### PR TITLE
[REG-1780] Add all parent objects to state for tree view on UI

### PR DESCRIPTION
**Pull request by RG-nAmKcAz**
- Adds a parentId field to all objects in the state data
  - Some objects may have a NULL parentId, if they do, they are at the top level of their respective scene hierarchy
- Includes all 'filler' parent objects to fill out the tree between renderable objects
  - Non-renderable or Off-Camera objects will have NULL screenSpaceBounds
  - DOES NOT include information about any children below the lowest child level objects with renderers
- **WARNING** (@addisonbgross) Removes the path/normalizedPath fields from the nested information like behaviours/colliders/rigidbodies/etc
  - If this will BREAK the UI, I can split it off into a separate PR to merged after the UI changes, just let me know

See also https://github.com/Regression-Games/RGBossRoom/pull/58 , which makes BossRoom spawn point deterministic

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

### CODE REVIEW

**Comment by addisonbgross** [comment]
@RG-nAmKcAz the removal of `path` and `normalizedPath` from behaviours will indeed cause an issue. If you don't mind separating that out into anoher PR, that would be awesome 👍🏻

**Comment by abeizer** [comment]
With the removal of `path` and `normalizedPath`, will this imply that any behaviours have the same path values as the entity?

**Review by vontell — APPROVED** [review]
Seems reasonable to me, but I'll leave @addisonbgross to review the particulars of the approach for his use case.

**Review by addisonbgross — APPROVED** [review]
Pending my comment about keeping the `path` and `normalizedPath` in behaviours/colliders/etc. this looks good

**Review by svolokh — APPROVED** [review]

**Comment by RG-nAmKcAz** [comment]
@abeizer 
`With the removal of path and normalizedPath, will this imply that any behaviours have the same path values as the entity?`

Correct.  These fields are removed because those things will only/always appear on their exact gameObject in the state.

**Comment by RG-nAmKcAz** [comment]
@addisonbgross path removal changes undone for this PR

Still be aware, you will be able to get NULL for screenSpaceBounds where the old code did not allow that... IOW... The UI might still get something it doesn't expect because of this PR, but not as catastrophic as the paths being gone :D

**Pull request merged**
