### PR TITLE
[REG-1716] Animation Rigging Extension Package

### PR DESCRIPTION
**Pull request by RG-nAmKcAz**
- Adds an extension package to support Animation Rigging

- Minor Inconvenience, but seems fine --- Unfortunately, Unity insists on not allowing packages to refer to other packages by git url... thus, users must manually add the core package for this to work.  You can't just add the extension pack and have it magically add the core package.

- If we are ok with this package style, I will add a documentation task to start tracking how to install our extension packages

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

### CODE REVIEW

**Review by vontell — APPROVED** [review]
Nice! Can you provide an example of the steps though for how this would be added? I see the bossroom example, but from your description in this PR, I was now confused on what the step is for adding this.

**Comment by RG-nAmKcAz** [comment]
@vontell You add it similarly to how you add our base package

from URL https://github.com/Regression-Games/RGUnityBots.git?path=src/gg.regression.unity.bots.animation.rigging#v0.0.19

The package will add just fine on its own, but won't compile correctly until you also add our base package

**Comment by vontell** [comment]
> @vontell You add it similarly to how you add our base package
> 
> from URL https://github.com/Regression-Games/RGUnityBots.git?path=src/gg.regression.unity.bots.animation.rigging#v0.0.19
> 
> The package will add just fine on its own, but won't compile correctly until you also add our base package

Ahhhh got it, awesome! That sounds great to me

**Review by svolokh — APPROVED** [review]
Looks good!

One thing I'm wondering about: for my legacy input manager work, I've needed to enable the `overrideReferences` flag to be able to pull in the `Mono.Cecil.Pdb.dll` library, which is an extension library for reading/writing PDB debug symbols so that we can preserve them after instrumentation. Do you think this will cause an issue for the extension system have here? (example shown below from my branch)

https://github.com/Regression-Games/RGUnityBots/blob/4da1412860112c94a901ce7d8cd8a858617ce720/src/gg.regression.unity.bots/Editor/Scripts/RegressionGames.Editor.asmdef#L11-L15

**Comment by RG-nAmKcAz** [comment]
> Looks good!
> 
> One thing I'm wondering about: for my legacy input manager work, I've needed to enable the `overrideReferences` flag to be able to pull in the `Mono.Cecil.Pdb.dll` library, which is an extension library for reading/writing PDB debug symbols so that we can preserve them after instrumentation. Do you think this will cause an issue for the extension system have here? (example shown below from my branch)
> 
> https://github.com/Regression-Games/RGUnityBots/blob/4da1412860112c94a901ce7d8cd8a858617ce720/src/gg.regression.unity.bots/Editor/Scripts/RegressionGames.Editor.asmdef#L11-L15

Since the extension system includes no pre-compiled items, I would highly doubt it.  Everything in the extension will be pulled in as source and built as part of their build.

**Pull request merged**
