### PR TITLE
[REG-2068] Handle ambiguous available segments in SequenceEditor UI by showing path

### PR DESCRIPTION
**Pull request by RG-nAmKcAz**
- Handles dis-ambiguating segments that have the same 'name' but different paths on the editor UI
  - If the segment has a name, then the name and path will be shown
  - If the segment DOES NOT have a name, then the path will be shown in place of the name, but the path sub text will be hidden
- Makes needed updates to the prefab to make decription/overlow expansion respect this new layout
- Stops setting the 'resourcePath' as the name on segments/segmentLists loaded from sequences and tracks the resourcePath separately.  This allows us to know if a user supplied name was truly set or not.

Long descriptions example with ...
image

Empty name example
image

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

### CODE REVIEW

**Review by addisonbgross — APPROVED** [review]

**Comment by batu** [comment]
This is an important feature but I think the overall aesthetics of our tool takes a step back. How difficult would it be do only show this extra information when it need disambiguation?

**Comment by RG-nAmKcAz** [comment]
> This is an important feature but I think the overall aesthetics of our tool takes a step back. How difficult would it be do only show this extra information when it need disambiguation?

That is what is already happening.  The information is only shown when a name is set.  Without this shown, finding your segment on disk or in the project required going 1 by 1 opening files to read names.

If you're asking if we can do this only when there are duplicate names... sure we probably could, but that didn't help me when I wanted to find that segment on disk.

**Comment by abeizer** [comment]
Functionally this is helpful, but aesthetically it makes things hard to visually parse.

Can we make the text smaller, possibly non-italic (if that looks good), and try a muted tone so that the name stands out the most and the path is there if the user wants to read it but it doesn't take center stage on the card? Not sure if you and @addisonbgross have talked about visual tweaks as a follow-up.

Also is there a way to see the entire path when it's sub-text? In your screenshot there's a bunch of `bot-segments/computer-vision/computer...` but if I can't see the end of the path then that won't always help me differentiate between segments with the same name.

**Comment by RG-nAmKcAz** [comment]
I have already opened a follow up task as this is needed on Segments tab as well.
https://linear.app/regression-games/issue/REG-2075/segment-cards-need-path-information

Right now.. this is completely un-usable in my environment.  If we don't merge this PR that is fine, but we need some similar change here immediately to resolve this.

As for UI styling... I'm not going to argue this beyond saying, I already spent about an hour with various colors, intensities, font sizings and layout spacings to get it to where I personally could easily see it.  I realize that others may not agree with those styling or color choices.  To get this to please everyone will involve re-thinking how those cards are styled altogether to fit this in nicely whereas this was meant as a PR for ... its not usable, get it working now.

**Comment by RG-nAmKcAz** [comment]
Here it is update without italics.
image

The ellipsis ... is mostly because our layout is too small compared to the screen space, I have a task open for next cycle to redo the Editor pane to takeup more of the screen space so we can widen the middle and right sections and show more details

https://linear.app/regression-games/issue/REG-2071/increase-the-dimensions-of-the-sequence-editor

**Comment by RG-nAmKcAz** [comment]
Gray update

image

**Review by abeizer — APPROVED** [review]

**Pull request merged**
