### PR TITLE
[REG-1099] Utils and env vars for CI/CD

### PR DESCRIPTION
**Pull request by vontell**
Adds a few features to the SDK to support CI/CD usage.

* A new "HasBotsRunning()" function that is used during tests to figure out when to terminate (see other PR at end of this description for an example)
* Adds API Key and Host env vars that can override the project settings in CI/CD

Example: https://github.com/Regression-Games/RGUnitySample/pull/6

### CODE REVIEW

**Comment by vontell** [comment]
@rcornwall-reg I'd like to get this merged quickly so I can test this new code with my sample (which is downloaded via github, so I need this to be on the main branch). Example here: https://github.com/Regression-Games/RGUnitySample/pull/6

Once I get that sample working, I will be making a tutorial with BossRoom.

**Review by rcornwall-reg — APPROVED** [review]
I don't see anything sensitive here, but is there any risk in keeping keys like API_KEY checked into our source?

**Comment by vontell** [comment]
@rcornwall-reg can you elaborate? With this code, the API Key is never checked into the source - it is added as an environment variable within the GitHub Actions secrets feature, so the API key will never be saved into a project or in the repo itself :D

**Comment by rcornwall-reg** [comment]
That's what I was wondering ^ Sounds good 👍

**Pull request merged**
