### PR TITLE
[REG-1099 Fix] Use Invoke instead of event button for button click

### PR DESCRIPTION
**Pull request by vontell**

### CODE REVIEW

**Review by RG-nAmKcAz — APPROVED** [review]
Approving only if this actually fixed the bossroom pipeline run issue

**Comment by vontell** [comment]
> Approving only if this actually fixed the bossroom pipeline run issue

Yup imma test the branch in CI and then go from there

**Review by abeizer — APPROVED** [review]

**Comment by vontell** [comment]
Didn't work :/

**Comment by RG-nAmKcAz** [comment]
should I try to recreate / debug ?

**Review by rcornwall-reg — APPROVED** [review]

**Comment by vontell** [comment]
@all I am going to close this for now because it didn't actually fix it 😬 will revisit and open a new PR when it makes sense to.

**Pull request closed without merging**
