### PR TITLE
[REG-1793] Initial ECS code

### PR DESCRIPTION
**Pull request by RG-nAmKcAz**
- Completely restructures the existing state recording and playback code to handle transforms and entities almost interchangeably
- Adds a new ECS SDK module to encapsulate the ECS code
  - **Add something like this to your packages manifest to enable this code ( "gg.regression.unity.bots.ecs": "file:C:/Users/zack/RG/RGUnityBots/src/gg.regression.unity.bots.ecs")**
- Moves all colliders, rigidbodies, behaviours to a single 'components' list (left the old arrays empty for now but in the json to avoid blowing up the client
- Adds Type (Entity or Transform) to all state entries
_See private Slack for more details_
---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

### CODE REVIEW

**Comment by RG-nAmKcAz** [comment]
@abeizer  FYI

**Review by svolokh — APPROVED** [review]
Looks good on my end. I will probably need to update my usage of the TransformStatus on the automated analysis action manager branch, but that should be straight-forward based on the changes I see in this PR.

**Review by vontell — COMMENTED** [review]
Still going through this review, but wanted to make sure there is a conversation on this between @abeizer, @addisonbgross, and @RG-nAmKcAz to ensure that the new data format is going to be supported in both the backend and the frontend. Has this format been recorded, and is there a plan for that yet?

**Comment by RG-nAmKcAz** [comment]
> Still going through this review, but wanted to make sure there is a conversation on this between @abeizer, @addisonbgross, and @RG-nAmKcAz to ensure that the new data format is going to be supported in both the backend and the frontend. Has this format been recorded, and is there a plan for that yet?

So today, bot segment files are versioned... State data is NOT.

We can start versioning state data from this PR forward and I think we should.  That would have helped on both this PR and the perframestatistics pr that we just merged.  

Thoughts / Agreement on adding versioning to state data ?

**Review by vontell — APPROVED** [review]

**Comment by vontell** [comment]
@RG-nAmKcAz yeah adding a version number would be great! With that in mind, however, @addisonbgross @abeizer I don't know if we have any switches yet or approaches on the backend and frontend for seeing and using the versions correctly, that's something we should think about.

**Comment by RG-nAmKcAz** [comment]
@vontell The bot segments code in the SDK very much uses the versions to support old vs new files and provide user feedback.

Since the backend no longer loads the state recording files, that will be a UI only processing for now.

**Comment by vontell** [comment]
@abeizer can you confirm this? Which files is the backend using for doing validations?

**Comment by RG-nAmKcAz** [comment]
@vontell the state files are used on the backend.. the bot segments are solely for use by the SDK

In the future when/if we have a bot segment builder that answer will change.

**Comment by RG-nAmKcAz** [comment]
Sample state file with entities and apiVersions on state

[1.json](https://github.com/user-attachments/files/16168912/1.json)

**Comment by addisonbgross** [comment]
I love the Entity / Transform delineation 👍🏻

**Review by abeizer — APPROVED** [review]

**Pull request merged**
